version: "3.9"

services:
  db:
    image: postgres:14.1
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
    networks:
      - network

  web:
    build: .
    image: flask-app
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    networks:
      - network
    depends_on:
      - db

networks:
    network:
